version: '3.8'

services:
  app:
    build: .
    container_name: pytest
    volumes:
      - .:/app
    command: pytest --cov=app --cov-report=term-missing
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
